### ISSUE TITLE
Avoiding prompting to edit configuration

### ISSUE THREAD

**Issue by LukeShortCloud** [toazd/ge-install-manager#4]
For automation purposes, it would be nice if there was at least an argument (`--no-edit-config` or similar) added to accept the default configuration and not be prompted to edit with `vim`.

```
$ ge-install-manager -i Proton-6.5-GE-2
Default configuration created at /home/user/.config/ge-install-manager/ge-install-manager.conf
Would you like to open it with vim?
```

As a workaround, I am copying a known-good configuration file over before running `ge-install-manager` for the first time.

On a related note, some users may not like/use Vim (I love Vim personally). You can have the user edit the configuration using the `$EDITOR` environment variable which is commonly set by shells to a default text editor (usually either `nano` or `vim`).

**Comment by toazd** [comment]
Your suggestion to bypass that check when a new configuration file is created is a very good one thank you!

Only short arguments are accepted by the script without a complete rewrite of the command line parsing function (`ParseParameters` lines 1891-1999)  so it would have to be a one letter argument that is not already in use.

The script already checks for and uses the `EDITOR` environment variable if it is set and a default configuration file is successfully created. Refer to lines 1623-1652 for more details.

**Comment by toazd** [comment]
A new command line parameter has been added to better facilitate automation (-A). Currently, adding it to the command line parameters during script invocation will skip two prompts that are typically shown during first run/install:
1. The prompt to edit a newly created config file if one does not exist
2. The prompt to create a symlink to the script at `~/.local/bin` or `/usr/local/sbin` if one does not exist

Thank you again for the suggestion. Please let me know if you have any issues or more suggestions.
