### ISSUE TITLE
Add argument to delete tarballs

### ISSUE THREAD

**Issue by LukeShortCloud** [toazd/ge-install-manager#5]
Currently, `Proton-<VERSION>-GE-<RELEASE>.tar.gz` tarballs are left in the `compatibilitytools.d` directory. Recent releases use about half a gigabyte.

It would be great to see a CLI argument to clean-up all tarballs. This could be used (1) when installing Proton releases and (2) by itself to clean all tarballs without installing anything.

1:

```
$ ge-install-manager -i Proton-6.16-GE-1 -c
```

2:

```
$ ge-install-manager -c
```

**Comment by toazd** [comment]
There are two existing arguments to assist with removing saved packages (tarballs). They are `-x` (remove all of them) and `-r <version>` (remove specified version).

Perhaps I should update the help output to include the word "tarballs" to be more clear what is meant by "saved packages." Thoughts?

**Comment by toazd** [comment]
The README file and help output from the script have been updated to better reflect what is meant by a "saved package."

Your first example use case ("when installing Proton releases") is covered by `-x`.

Your second example use case ("by itself to clean all tarballs without installing anything") would require substantial restructuring of the entire script when a simple command by itself can handle that eg. `rm ~/.steam/root/compatibilitytools.d/Proton-*.gz`.

Please reopen this issue and/or let me know if I misinterpreted your suggestions.

**Comment by LukeShortCloud** [comment]
Thanks for the clarification! I misunderstood and/or missed that argument. I've been using a similar `rm` command as a workaround. Using the `-x` during the installation should be exactly what I need.
